// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.
#include <stdio.h>
#include <stdlib.h>
#define P 1000000007L
#define WINDOW 512
#define MIN_MATCH 3
#define MAX_MATCH 255
#define ALPHA 6
static long lcg(long s){ return (s*1103515245L+12345L)&0x7fffffffL; }
int main(int argc,char**argv){
    int N = argc>1?atoi(argv[1]):24000;
    unsigned char *in = malloc(N);
    long s=42;
    for(int i=0;i<N;i++){ s=lcg(s); in[i]=(unsigned char)(s%ALPHA); }
    int pos=0; long h=0;
    while(pos<N){
        int best_len=0, best_dist=0;
        int start = pos-WINDOW; if(start<0) start=0;
        for(int cand=pos-1; cand>=start; cand--){          // closest distance first
            int l=0;
            while(pos+l<N && l<MAX_MATCH && in[cand+l]==in[pos+l]) l++;
            if(l>best_len){ best_len=l; best_dist=pos-cand; } // strict > : closest wins ties
        }
        if(best_len>=MIN_MATCH){
            h=(h*31+1)%P; h=(h*31+best_dist)%P; h=(h*31+best_len)%P;
            pos+=best_len;
        } else {
            h=(h*31+0)%P; h=(h*31+in[pos])%P;
            pos+=1;
        }
    }
    printf("%ld\n",h); printf("lz77(%d)\n",N);
    return 0;
}
