// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.

class Lz77 {
    static final long P = 1000000007L;
    static final int WINDOW = 512;
    static final int MIN_MATCH = 3;
    static final int MAX_MATCH = 255;
    static final int ALPHA = 6;

    static long lz77(int n) {
        int[] input = new int[n];
        long s = 42L;
        for (int i = 0; i < n; i++) {
            s = (s * 1103515245L + 12345L) & 0x7fffffffL;
            input[i] = (int) (s % ALPHA);
        }
        int pos = 0;
        long h = 0L;
        while (pos < n) {
            int bestLen = 0;
            int bestDist = 0;
            int start = pos - WINDOW;
            if (start < 0) start = 0;
            int cand = pos - 1;
            while (cand >= start) {   // closest distance first
                int len = 0;
                while (pos + len < n && len < MAX_MATCH && input[cand + len] == input[pos + len]) len++;
                if (len > bestLen) { bestLen = len; bestDist = pos - cand; }   // strict > : closest wins ties
                cand--;
            }
            if (bestLen >= MIN_MATCH) {
                h = (h * 31 + 1) % P; h = (h * 31 + bestDist) % P; h = (h * 31 + bestLen) % P;
                pos += bestLen;
            } else {
                h = (h * 31 + 0) % P; h = (h * 31 + input[pos]) % P;
                pos += 1;
            }
        }
        return h;
    }

    public static void main(String[] args) {
        int n = args.length > 0 ? Integer.parseInt(args[0]) : 24000;
        System.out.println(lz77(n));
        System.out.println("lz77(" + n + ")");
    }
}
