// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.

const val P = 1000000007L
const val WINDOW = 512
const val MIN_MATCH = 3
const val MAX_MATCH = 255
const val ALPHA = 6

fun lz77(n: Int): Long {
    val input = IntArray(n)
    var s = 42L
    for (i in 0 until n) {
        s = (s * 1103515245L + 12345L) and 0x7fffffffL
        input[i] = (s % ALPHA).toInt()
    }
    var pos = 0
    var h = 0L
    while (pos < n) {
        var bestLen = 0
        var bestDist = 0
        var start = pos - WINDOW
        if (start < 0) start = 0
        var cand = pos - 1
        while (cand >= start) {                                  // closest distance first
            var len = 0
            while (pos + len < n && len < MAX_MATCH && input[cand + len] == input[pos + len]) len++
            if (len > bestLen) { bestLen = len; bestDist = pos - cand }  // strict > : closest wins ties
            cand--
        }
        if (bestLen >= MIN_MATCH) {
            h = (h * 31 + 1) % P; h = (h * 31 + bestDist) % P; h = (h * 31 + bestLen) % P
            pos += bestLen
        } else {
            h = (h * 31 + 0) % P; h = (h * 31 + input[pos]) % P
            pos += 1
        }
    }
    return h
}

fun main(args: Array<String>) {
    val n = if (args.isNotEmpty()) args[0].toInt() else 24000
    println(lz77(n))
    println("lz77($n)")
}
