// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.
using System;

class Lz77
{
    const long P = 1000000007L;
    const int WINDOW = 512;
    const int MIN_MATCH = 3;
    const int MAX_MATCH = 255;
    const int ALPHA = 6;

    static long Run(int n)
    {
        byte[] input = new byte[n];
        long s = 42;
        for (int i = 0; i < n; i++)
        {
            s = (s * 1103515245L + 12345L) & 0x7fffffffL;
            input[i] = (byte)(s % ALPHA);
        }

        int pos = 0;
        long h = 0;
        while (pos < n)
        {
            int bestLen = 0, bestDist = 0;
            int start = pos - WINDOW; if (start < 0) start = 0;
            for (int cand = pos - 1; cand >= start; cand--)          // closest distance first
            {
                int l = 0;
                while (pos + l < n && l < MAX_MATCH && input[cand + l] == input[pos + l]) l++;
                if (l > bestLen) { bestLen = l; bestDist = pos - cand; } // strict > : closest wins ties
            }
            if (bestLen >= MIN_MATCH)
            {
                h = (h * 31 + 1) % P; h = (h * 31 + bestDist) % P; h = (h * 31 + bestLen) % P;
                pos += bestLen;
            }
            else
            {
                h = (h * 31 + 0) % P; h = (h * 31 + input[pos]) % P;
                pos += 1;
            }
        }
        return h;
    }

    static void Main(string[] args)
    {
        int n = args.Length > 0 ? int.Parse(args[0]) : 24000;
        Console.WriteLine(Run(n));
        Console.WriteLine($"lz77({n})");
    }
}
