# polymorphism: the dynamic-dispatch / virtual-call-overhead axis. N=10000 objects of K=6 concrete
# types are generated by an LCG (type from the high bits, fields a,b,c mod 1000) and kept in
# generation order, so the call site stays MEGAMORPHIC (K=6 > a typical polymorphic-inline-cache,
# unpredictable order -> no devirtualization). We then fold an accumulator through every object,
# M passes: acc = Apply.apply(obj, acc). Which body runs is resolved at RUNTIME from the object's
# type. acc threads through every call (a strict data dependency) and each formula uses a large
# distinct multiplier, so the per-pass map never reaches a fixed point -> the checksum depends on M
# (proof all N*M dispatches ran).
#
# Elixir's idiomatic runtime polymorphism is a PROTOCOL: `Apply` declares apply/2, and the six
# `defimpl` blocks are the six per-type bodies. `Apply.apply(obj, acc)` dispatches on the struct's
# type at runtime via the protocol's dispatch table - the BEAM analogue of a vtable / interface
# call, NOT a source-level type tag + switch (which the fairness rules forbid). Immutable: acc is
# threaded through Enum.reduce. Pure integer (Elixir ints are arbitrary precision; all values stay
# < P^2 so the `rem(_, P)` after every step keeps them bounded).
defprotocol Apply do
  def apply(obj, x)
end

# The six structs all carry the same fields a, b, c; each defimpl is one type's "virtual method".
defmodule T0, do: defstruct([:a, :b, :c])
defmodule T1, do: defstruct([:a, :b, :c])
defmodule T2, do: defstruct([:a, :b, :c])
defmodule T3, do: defstruct([:a, :b, :c])
defmodule T4, do: defstruct([:a, :b, :c])
defmodule T5, do: defstruct([:a, :b, :c])

defimpl Apply, for: T0 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 1_000_003 + o.a, @p)
end

defimpl Apply, for: T1 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 998_273 + o.b, @p)
end

defimpl Apply, for: T2 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 999_983 + o.c, @p)
end

defimpl Apply, for: T3 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 997_879 + o.a + o.b, @p)
end

defimpl Apply, for: T4 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 996_323 + o.b * o.c, @p)
end

defimpl Apply, for: T5 do
  @p 1_000_000_007
  def apply(o, x), do: rem(x * 995_369 + o.a + o.c, @p)
end

defmodule Polymorphism do
  import Bitwise
  @n 10_000
  @k 6
  @types {T0, T1, T2, T3, T4, T5}

  # glibc-style LCG, masked to 31 bits (matches the C `lcg`).
  defp lcg(s), do: band(s * 1_103_515_245 + 12_345, 0x7FFFFFFF)

  # Build the N objects in LCG generation order (megamorphic order preserved). Returns {objs, _}.
  defp build_objs do
    {objs, _s} =
      Enum.map_reduce(1..@n, 42, fn _i, s ->
        s = lcg(s)
        t = rem(bsr(s, 16), @k)
        s = lcg(s)
        a = rem(s, 1000)
        s = lcg(s)
        b = rem(s, 1000)
        s = lcg(s)
        c = rem(s, 1000)
        {struct(elem(@types, t), a: a, b: b, c: c), s}
      end)

    objs
  end

  def run(m) do
    objs = build_objs()

    Enum.reduce(1..m, 1, fn _pass, acc ->
      Enum.reduce(objs, acc, fn obj, a -> Apply.apply(obj, a) end)
    end)
  end
end

m =
  case System.argv() do
    [a | _] -> String.to_integer(a)
    _ -> 50
  end

IO.puts(Polymorphism.run(m))
IO.puts("polymorphism(#{m})")
