// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.
use std::env;

const P: i64 = 1000000007;
const WINDOW: i32 = 512;
const MIN_MATCH: i32 = 3;
const MAX_MATCH: i32 = 255;
const ALPHA: i64 = 6;

fn run(n: i32) -> i64 {
    let mut input: Vec<u8> = vec![0; n as usize];
    let mut s: i64 = 42;
    for i in 0..n as usize {
        s = (s * 1103515245 + 12345) & 0x7fffffff;
        input[i] = (s % ALPHA) as u8;
    }

    let mut pos: i32 = 0;
    let mut h: i64 = 0;
    while pos < n {
        let mut best_len: i32 = 0;
        let mut best_dist: i32 = 0;
        let start = if pos - WINDOW < 0 { 0 } else { pos - WINDOW };
        let mut cand = pos - 1;
        while cand >= start {
            // closest distance first
            let mut l: i32 = 0;
            while pos + l < n
                && l < MAX_MATCH
                && input[(cand + l) as usize] == input[(pos + l) as usize]
            {
                l += 1;
            }
            if l > best_len {
                // strict > : closest wins ties
                best_len = l;
                best_dist = pos - cand;
            }
            cand -= 1;
        }
        if best_len >= MIN_MATCH {
            h = (h * 31 + 1) % P;
            h = (h * 31 + best_dist as i64) % P;
            h = (h * 31 + best_len as i64) % P;
            pos += best_len;
        } else {
            h = (h * 31 + 0) % P;
            h = (h * 31 + input[pos as usize] as i64) % P;
            pos += 1;
        }
    }
    h
}

fn main() {
    let n: i32 = env::args().nth(1).and_then(|s| s.parse().ok()).unwrap_or(24000);
    println!("{}", run(n));
    println!("lz77({})", n);
}
