// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.
package main

import (
	"fmt"
	"os"
	"strconv"
)

const (
	P         = 1000000007
	WINDOW    = 512
	MIN_MATCH = 3
	MAX_MATCH = 255
	ALPHA     = 6
)

func run(n int) int64 {
	in := make([]byte, n)
	s := int64(42)
	for i := 0; i < n; i++ {
		s = (s*1103515245 + 12345) & 0x7fffffff
		in[i] = byte(s % ALPHA)
	}
	pos := 0
	var h int64 = 0
	for pos < n {
		bestLen, bestDist := 0, 0
		start := pos - WINDOW
		if start < 0 {
			start = 0
		}
		for cand := pos - 1; cand >= start; cand-- { // closest distance first
			l := 0
			for pos+l < n && l < MAX_MATCH && in[cand+l] == in[pos+l] {
				l++
			}
			if l > bestLen { // strict > : closest wins ties
				bestLen = l
				bestDist = pos - cand
			}
		}
		if bestLen >= MIN_MATCH {
			h = (h*31 + 1) % P
			h = (h*31 + int64(bestDist)) % P
			h = (h*31 + int64(bestLen)) % P
			pos += bestLen
		} else {
			h = (h*31 + 0) % P
			h = (h*31 + int64(in[pos])) % P
			pos++
		}
	}
	return h
}

func main() {
	n := 24000
	if len(os.Args) > 1 {
		if v, err := strconv.Atoi(os.Args[1]); err == nil {
			n = v
		}
	}
	fmt.Println(run(n))
	fmt.Printf("lz77(%d)\n", n)
}
