import Foundation

// lz77: a hand-written LZ77 compressor - the data-compression / sliding-window axis. Compress an
// LCG-generated byte stream (small alphabet, so matches are common): at each position scan the
// previous WINDOW bytes for the longest match (closest wins ties), emit a (distance,length)
// back-reference or a literal, advance greedily. Reduce the token stream to a polynomial hash.
// No compression library; all integer-deterministic.

let P = 1000000007
let WINDOW = 512
let MIN_MATCH = 3
let MAX_MATCH = 255
let ALPHA = 6

func lcg(_ s: Int) -> Int {
    return (s &* 1103515245 &+ 12345) & 0x7fffffff
}

func run(_ n: Int) -> Int {
    var input = [UInt8](repeating: 0, count: n)
    var s = 42
    for i in 0..<n {
        s = lcg(s)
        input[i] = UInt8(s % ALPHA)
    }

    var pos = 0
    var h = 0
    while pos < n {
        var bestLen = 0
        var bestDist = 0
        var start = pos - WINDOW
        if start < 0 { start = 0 }
        var cand = pos - 1
        while cand >= start {                                 // closest distance first
            var l = 0
            while pos + l < n && l < MAX_MATCH && input[cand + l] == input[pos + l] { l += 1 }
            if l > bestLen { bestLen = l; bestDist = pos - cand } // strict > : closest wins ties
            cand -= 1
        }
        if bestLen >= MIN_MATCH {
            h = (h * 31 + 1) % P
            h = (h * 31 + bestDist) % P
            h = (h * 31 + bestLen) % P
            pos += bestLen
        } else {
            h = (h * 31 + 0) % P
            h = (h * 31 + Int(input[pos])) % P
            pos += 1
        }
    }
    return h
}

let n = CommandLine.arguments.count > 1 ? (Int(CommandLine.arguments[1]) ?? 24000) : 24000
print(run(n))
print("lz77(\(n))")
